apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
  - name: http
    protocol: {{ .Values.service.protocol }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.ports.containerPort}}
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }}